AppBibliotecaWebG1/Models/DbContextBiblioteca.cs
using Microsoft.EntityFrameworkCore;

namespace AppBibliotecaWebG1.Models
{
    //Muy importante que la clase Herede de la clase padre DbContext
    public class DbContextBiblioteca : DbContext
    {
        /// <summary>
        /// Constructor con parámetros recibe la referencia del  ORM
        /// </summary>
        /// <param name="options"></param>
        public DbContextBiblioteca(DbContextOptions<DbContextBiblioteca> options) : base(options)
        {

        }
        //Propiedad  DbSet que permite dar mantenimiento al catalogo de libros
        public DbSet<Libro> Libros { get; set; }

        //Método encargado de crear la table para el entidad en la db
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Libro>().HasData(new Libro()
            {
                ISBN = 1,
                Titulo = "Lenguajes de programación",
                Editorial = "Puntarenas",
                PrecioVenta = 27500,
                Foto="ND",
                FechaPublicacion = DateTime.Now,
                Estado = 'A'
            });
        }

    } //cierre class
} //cierre namespace

AppBibliotecaWebG1/Models/ErrorViewModel.cs
namespace AppBibliotecaWebG1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AppBibliotecaWebG1/Models/Libro.cs
using System.ComponentModel.DataAnnotations;

namespace AppBibliotecaWebG1.Models
{
    public class Libro
    {
        [Key]
        public int ISBN { get; set; }

        [Required(ErrorMessage = "Debe ingresar el titulo")]
        [DataType(DataType.Text)]
        [StringLength(100)]
        public string Titulo { get; set; }

        [Required(ErrorMessage = "No se permite la editoria en blanco")]
        [DataType(DataType.Text)]
        [StringLength(150)]
        public string Editorial { get; set; }


        [Required(ErrorMessage = "Debe ingresar un valor valido")]
        [DisplayFormat(DataFormatString = "{0:C0}")]
        [Range(0, Int32.MaxValue)]
        public decimal PrecioVenta
        {
            get;set;
        }

        [Required(ErrorMessage = "Seleccione la foto")]
        [DataType(DataType.Text)]
        public string Foto { get; set; }

        [Required(ErrorMessage = "Debe seleccionar la fecha")]
        [DataType(DataType.Date)]
        //[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime FechaPublicacion { get; set; }

        [Required(ErrorMessage = "Seleccione un estado")]
        public char Estado { get; set; }


    }
}

AppBibliotecaWebG1/Controllers/HomeController.cs
using AppBibliotecaWebG1.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AppBibliotecaWebG1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AppBibliotecaWebG1/Controllers/LibrosController.cs
using Microsoft.AspNetCore.Mvc;
//Se referencia el  ORM
using AppBibliotecaWebG1.Models;
using Microsoft.EntityFrameworkCore;

namespace AppBibliotecaWebG1.Controllers
{
    public class LibrosController : Controller
    {
        //Variable que permite manejar la referencia del contexto
        private readonly DbContextBiblioteca _context = null;

        /// <summary>
        /// Constructor con parámetros recibe la referencia del ORM
        /// </summary>
        /// <param name="context"></param>
        public LibrosController(DbContextBiblioteca context)
        {
            _context = context; //se asigna la referencia del contexto 
        }


        public async Task<IActionResult> Index()
        {
            //se declara la variable lista
            //por medio del ORM se lee la información de todos los libros en la db
            var listado = await _context.Libros.ToListAsync();

            return View(listado);//Se envia el listado al front-end
        }

        //Métodos encargado para almacenar un libro
        [HttpGet]
        public IActionResult Create() //Método encargado de mostrar el front-end para crear un libro
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind]Libro libro)
        {
            if(libro == null) //se valida que el objeto libro tenga datos
            {
                return View(); //Como no hay datos dejamos al usuario dentro del formulario create
            }
            else
            {  //si hay datos almacenamos el libro
                _context.Libros.Add(libro);

                //se aplican los cambios en la db
                await _context.SaveChangesAsync();

                //ubicamos al usuario dentro del listado libros
                return RedirectToAction("Index");
                
            }
        }


        //Métodos para el proceso de eliminar un libro
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            //buscar e libro  a eliminar por medio del  ORM
            var temp  = await _context.Libros.FirstOrDefaultAsync(r => r.ISBN == id);

            //se envian los datos del libro al front-end
            return View(temp);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>Delete(int? id)
        {
            //se busca por el ISBN el libro  a eliminar
            var temp = await _context.Libros.FirstOrDefaultAsync(r => r.ISBN == id);

            if(temp != null) //se valida si tiene datos
            {
                _context.Libros.Remove(temp); //se elimina el libro
                await _context.SaveChangesAsync();  //se aplican los cambios
                return RedirectToAction("Index");//se muestra la lista de libros
            }
            else
            {
                return NotFound(); //Error 404 recurso no disponible
            }
        }


        //Método encargado de mostrar los datos para un libro especifico
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            //se busca por ISBN el libro a mostrar
            var temp = await _context.Libros.FirstOrDefaultAsync(r => r.ISBN == id);

            //se envian los datos al front-end
            return View(temp);
        }


        //Métodos encargados de realizar el proceso de editar los datos a un libro
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            //se busca por el ISBN  los datos del a editar
            var temp  = await _context.Libros.FirstOrDefaultAsync(r =>r.ISBN == id);

            //se envia los datos del libro al front-end
            return View(temp);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>Edit(int id, [Bind]Libro plibro)
        {
            //validacion del ID
            if(id == plibro.ISBN)
            {
                //se busca el libro anterior con sus datos
                var  temp = await _context.Libros.FirstOrDefaultAsync( r => r.ISBN == id);

                _context.Libros.Remove(temp); //se elimina el libro
                _context.Libros.Add(plibro); //se agrega el libro
                await _context.SaveChangesAsync(); //se aplican los cambios

                //se ubica al usuario dentro del listado de libros
                return RedirectToAction("Index");

            }
            else
            {
                return NotFound();//Recurso no disponible
            }
        }



    } //cierre controller
} //cierre namepaces

AppBibliotecaWebG1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AppBibliotecaWebG1/Views/Libros/Create.cshtml
@model AppBibliotecaWebG1.Models.Libro

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Libro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ISBN" class="control-label"></label>
                <input asp-for="ISBN" class="form-control" />
                <span asp-validation-for="ISBN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Editorial" class="control-label"></label>
                <input asp-for="Editorial" class="form-control" />
                <span asp-validation-for="Editorial" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrecioVenta" class="control-label"></label>
                <input asp-for="PrecioVenta" class="form-control" />
                <span asp-validation-for="PrecioVenta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Foto" class="control-label"></label>
                <input asp-for="Foto" class="form-control" />
                <span asp-validation-for="Foto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaPublicacion" class="control-label"></label>
                <input asp-for="FechaPublicacion" class="form-control" />
                <span asp-validation-for="FechaPublicacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>

                 <select asp-for="Estado" class="form-control">
                     <option selected="selected" value="A">Activo</option>
                     <option value="I">Inactivo</option>
                     <option value="G">Agotado</option>
                 </select>

                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary mt-3" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary mt-3">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppBibliotecaWebG1/Views/Libros/Delete.cshtml
@model AppBibliotecaWebG1.Models.Libro

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Libro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ISBN)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Editorial)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Editorial)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrecioVenta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrecioVenta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Foto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Foto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaPublicacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaPublicacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
    
    <form asp-action="Delete">

        <input type="button" value="Delete" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#ModalConfirmar" /> |

        <a asp-action="Index" class="btn btn-secondary">Back to List</a>

        <!-- Modal -->
        <div class="modal fade" id="ModalConfirmar" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Confirmar acción ?</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        Desea eliminar el  libro @Model.Titulo ?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary"> Ok </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

AppBibliotecaWebG1/Views/Libros/Details.cshtml
@model AppBibliotecaWebG1.Models.Libro

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Libro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ISBN)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Editorial)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Editorial)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrecioVenta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrecioVenta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Foto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Foto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaPublicacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaPublicacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new {  id = Model.ISBN }, new{@class="btn btn-primary"}) |
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

AppBibliotecaWebG1/Views/Libros/Edit.cshtml
@model AppBibliotecaWebG1.Models.Libro

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Libro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ISBN" class="control-label"></label>
                <input asp-for="ISBN" class="form-control" readonly />
                <span asp-validation-for="ISBN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Editorial" class="control-label"></label>
                <input asp-for="Editorial" class="form-control" />
                <span asp-validation-for="Editorial" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrecioVenta" class="control-label"></label>
                <input asp-for="PrecioVenta" value=@Model.PrecioVenta.ToString("0.00") class="form-control" />
                <span asp-validation-for="PrecioVenta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Foto" class="control-label"></label>
                <input asp-for="Foto" class="form-control" />
                <span asp-validation-for="Foto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaPublicacion" class="control-label"></label>
                <input asp-for="FechaPublicacion" class="form-control" />
                <span asp-validation-for="FechaPublicacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>

                <select asp-for="Estado" class="form-control">
                    <option selected value="A">Activo</option>
                    <option value="I">Inactivo</option>
                    <option value="G">Agotado</option>
                </select>
                
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary mt-3" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary mt-3">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppBibliotecaWebG1/Views/Libros/Index.cshtml
@model IEnumerable<AppBibliotecaWebG1.Models.Libro>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ISBN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Editorial)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrecioVenta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Foto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaPublicacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ISBN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Editorial)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrecioVenta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Foto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaPublicacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>

                @Html.ActionLink("Edit", "Edit", new {  id=item.ISBN  },new{@class="btn btn-info"}) |
                

                @Html.ActionLink("Details", "Details", new {  id=item.ISBN  },new{@class="btn btn-secondary"}) |
                

                @Html.ActionLink("Delete", "Delete", new {  id=item.ISBN },new{@class="btn btn-warning"})

            </td>
        </tr>
}
    </tbody>
</table>

AppBibliotecaWebG1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppBibliotecaWebG1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AppBibliotecaWebG1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppBibliotecaWebG1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Libros" asp-action="Index">Libros</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AppBibliotecaWebG1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>